version: '3.8'

services:
  # mysql-keycloak:
  #   image: mysql:5.7
  #   # or use the version of your choice
  #   container_name: keycloak_sql
  #   environment:
  #     MYSQL_DATABASE: keycloak
  #     MYSQL_USER: keycloak
  #     MYSQL_PASSWORD: keycloak
  #     MYSQL_ROOT_PASSWORD: root
  #   # volumes:
  #   #   - mysql_data:/var/lib/mysql
  #   #   - ./init.sql:/docker-entrypoint-initdb.d/init.sql
  #   ports:
  #     - "3310:3306"
  # keycloak:
  #   image: quay.io/keycloak/keycloak:latest
  #   container_name: keycloak
  #   environment:
  #     KEYCLOAK_USER: admin
  #     KEYCLOAK_PASSWORD: admin
  #     KC_HOSTNAME: localhost
  #     KC_DB: mysql
  #     KC_DB_URL: jdbc:mysql://mysql-keycloak:3306/keycloak?useSSL=false
  #     KC_DB_USERNAME: keycloak
  #     KC_DB_PASSWORD: keycloak
  #     KEYCLOAK_ADMIN: admin # Change to your preferred admin username
  #     KEYCLOAK_ADMIN_PASSWORD: admin
  #   ports:
  #     - "8089:8080"
  #   volumes:
  #     - ./keycloak/config:/opt/keycloak/data/import
  #   command:
  #     - start-dev --import-realm
  #     - --file=/opt/jboss/keycloak/imports/config.json
  #   depends_on:
  #     - mysql-keycloak

  keycloak:
    image: quay.io/keycloak/keycloak:latest
    container_name: keycloak
    # restart: on-failure
    environment:
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
      KC_HOSTNAME: localhost
      # KC_DB: mysql
      # KC_DB_URL: jdbc:mysql://feedverse-post.cfzjlkfchdrk.us-east-2.rds.amazonaws.com/feedverse
      # KC_DB_USERNAME: admin
      # KC_DB_PASSWORD: yXDMxtW64hRBTAysECxf
      KEYCLOAK_ADMIN: admin # Change to your preferred admin username
      KEYCLOAK_ADMIN_PASSWORD: admin
      DB_POOL_MAX_SIZE: 50
    ports:
      - "8089:8080"
    volumes:
      - ./keycloak/config:/opt/keycloak/data/import
    command:
      - start-dev
      - --import-realm
      # - --db-pool-initial-size 10
      - --file=/opt/jboss/keycloak/imports/config.json
    # depends_on:
    #   - mysql-keycloak

    # neo4j:
    #   image: neo4j:latest
    #   container_name: neo4j
    #   environment:
    #     NEO4J_AUTH: neo4j/12345678
    #   ports:
    #     - "7474:7474"
    #     - "7687:7687"

    # postgres:
    #   image: postgres:latest
    #   container_name: my_postgres
    #   environment:
    #     POSTGRES_DB: feedverse
    #     POSTGRES_USER: feedverse
    #     POSTGRES_PASSWORD: feedverse
    #   ports:
    #     - "5432:5432"

  zookeeper:
    image: wurstmeister/zookeeper
    container_name: zookeeper
    restart: on-failure
    ports:
      - "2181:2181"
  kafka:
    image: wurstmeister/kafka
    container_name: kafka
    restart: on-failure
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    depends_on:
      - zookeeper

  feedverse_authenticator_service:
    build: ./Backend/feedverse-authenticator/authenticator/
    depends_on:
      - keycloak
      # - neo4j
    ports:
      - "8081:8008"
    environment:
      # - NEO4J_URL=bolt://neo4j:7687
      - SPRING_DATASOURCE_URL=jdbc:mysql://feedverse-post.cfzjlkfchdrk.us-east-2.rds.amazonaws.com/feedverse
      - SPRING_DATASOURCE_USERNAME=admin
      - SPRING_DATASOURCE_PASSWORD=yXDMxtW64hRBTAysECxf
      - KEYCLOAK_URL=http://keycloak:8080

  feedverse_user_service:
    build: ./Backend/userservices/userservices
    depends_on:
      - keycloak
      # - neo4j
      - kafka
    ports:
      - "8082:8010"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://feedverse-post.cfzjlkfchdrk.us-east-2.rds.amazonaws.com/feedverse
      - SPRING_DATASOURCE_USERNAME=admin
      - SPRING_DATASOURCE_PASSWORD=yXDMxtW64hRBTAysECxf
      - KEYCLOAK_URL=http://keycloak:8080
      - KEYCLOAK_AUTH=http://keycloak:8080/realms/feedverse/protocol/openid-connect/certs
      - KAFKA_SERVER=kafka:9092

  posts_service:
    build: ./Backend/posts/posts
    container_name: feedverse_posts_service
    depends_on:
      - keycloak
      - kafka
    ports:
      - "8083:8084"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://feedverse-post.cfzjlkfchdrk.us-east-2.rds.amazonaws.com/feedverse
      - SPRING_DATASOURCE_USERNAME=admin
      - SPRING_DATASOURCE_PASSWORD=yXDMxtW64hRBTAysECxf
      - KEYCLOAK_URL=http://keycloak:8080
      - KEYCLOAK_AUTH=http://keycloak:8080/realms/feedverse/protocol/openid-connect/certs
      - KAFKA_SERVER=kafka:9092
volumes:
  mysql_data:
