version: '3'

services:
  mysql:
    image: mysql:5.7 # or use the version of your choice
    environment:
      MYSQL_DATABASE: keycloak
      MYSQL_USER: keycloak
      MYSQL_PASSWORD: keycloak
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3310:3306"

  keycloak:
    image: quay.io/keycloak/keycloak:latest
    environment:
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
      KC_HOSTNAME: localhost
      KC_DB: mysql
      KC_DB_URL: jdbc:mysql://mysql:3306/keycloak?useSSL=false
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: keycloak
      KEYCLOAK_ADMIN: admin # Change to your preferred admin username
      KEYCLOAK_ADMIN_PASSWORD: admin
    ports:
      - "8089:8080"
    volumes:
      - ./config:/opt/keycloak/data/import
    command:
      - start-dev --import-realm
      - --file=/opt/jboss/keycloak/imports/config.json

    depends_on:
      - mysql

volumes:
  mysql_data:
